baseURL = "https://reinnatalia25.github.io/portfolio/"
languageCode = "en-us"
title = "Natalia Reinoso | Economics & Data Analytics"

[params]
author = "Natalia Reinoso"
description = "Economics graduate from William & Mary with a minor in Data Science."
